name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    environment: readonly-ftx
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: FTX_KEY=${FTX_KEY_READONLY} FTX_SECRET=${FTX_SECRET_READONLY} swift test -v
